plugins {
    id 'com.android.library'
}

android {
    namespace 'org.cocos2dx.lib'
    compileSdk PROP_COMPILE_SDK_VERSION.toInteger()

    defaultConfig {
        minSdk PROP_MIN_SDK_VERSION.toInteger()
        targetSdk PROP_TARGET_SDK_VERSION.toInteger()
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            aidl.srcDirs '../java/src'
            java.srcDirs '../java/src'
        }
    }

    buildTypes {
        release {
            consumerProguardFiles 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        aidl true
    }
}

dependencies {
    implementation fileTree(dir: '../java/libs', include: ['*.jar'])
}
