plugins {
    id 'com.android.application'
}

def cocos2dxRootPath = rootProject.projectDir.toPath()
    .resolve('../../../..')
    .normalize()
    .toFile()

android {
    namespace 'org.cocos2dx.lua_empty_test'
    compileSdk PROP_COMPILE_SDK_VERSION.toInteger()

    ndkVersion PROP_NDK_VERSION

    defaultConfig {
        applicationId 'org.cocos2dx.lua_empty_test'
        minSdk PROP_MIN_SDK_VERSION.toInteger()
        targetSdk PROP_TARGET_SDK_VERSION.toInteger()
        versionCode 1
        versionName '1.0'

        externalNativeBuild {
            cmake {
                targets 'lua_empty_test'
                arguments '-DANDROID_STL=c++_static'
                cppFlags '-frtti -fexceptions -fsigned-char'
            }
        }

        ndk {
            abiFilters.addAll(PROP_APP_ABI.split(':'))
        }
    }

    sourceSets {
        main {
            assets.srcDir 'src/main/assets'
        }
    }

    externalNativeBuild {
        cmake {
            path file('../../CMakeLists.txt')
            version PROP_CMAKE_VERSION
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    signingConfigs {
        release {
            if (project.hasProperty('RELEASE_STORE_FILE')) {
                storeFile file(RELEASE_STORE_FILE)
                storePassword RELEASE_STORE_PASSWORD
                keyAlias RELEASE_KEY_ALIAS
                keyPassword RELEASE_KEY_PASSWORD
            }
        }
    }

    buildTypes {
        debug {
            jniDebuggable true
        }

        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                'proguard-rules.pro'
            if (project.hasProperty('RELEASE_STORE_FILE')) {
                signingConfig signingConfigs.release
            }
        }
    }
}

ext.cocosLuaAssets = [
    engineRoot: cocos2dxRootPath,
    resources: [
        [from: file('../../../res'), into: 'res'],
        [from: file('../../../src'), into: 'src'],
        [
            from: new File(
                cocos2dxRootPath,
                'cocos/scripting/lua-bindings/script'
            ),
            into: 'src/cocos'
        ]
    ]
]
apply from: new File(
    cocos2dxRootPath,
    'tools/cocos2d-console/plugins/plugin_luacompile/cocos-lua-assets.gradle'
)

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':libcocos2dx')
}
